### ISSUE TITLE
Is page offset supported while getting multiple results for resources?

### ISSUE THREAD

**Issue by saichint** [beda-software/aidbox-py#9]
Hi,
I am using aidbox-py in our project.
Basically, I have created multiple "patient" resources.
When I am doing a search using:
client.resources('Patient').search(name='Smith').fetch_all()
I am getting all the resources.
I can use limit(x) to get the first x results.
client.resources('Patient').search(name='Smith').limit(10).fetch()

But, if I want to get the results by page (for getting next 10 results), how to pass offset to this API? I could not find anything other than page.
client.resources('Patient').search(name='Smith').page(1).fetch()
When I try with this, it fails saying that "'SyncAidBoxSearchSet' object has no attribute 'page'".
Is there a different way to give offset to get the next set of results?
Please help?
Thanks in advance,
Sai

**Comment by ruscoder** [comment]
Hi @saichint!

This library is an extension of https://github.com/beda-software/fhir-py for Aidbox.
FHIR specification does not declare how FHIR servers should return a paginated result. Some FHIR servers don't provide any abilities to fetch a certain page. So, fhir-py library does not have this functionality, and this library does not have this functionality either.

You can create PR for this library.

As a fast workaround you can try to use:
```
client.resources('Patient').search(_page=2).fetch()
```

**Comment by saichint** [comment]
I tried
client.resources('Patient').search(_page=2).fetch()
I got 0 results back! I tried with _page=0, _page=1 as well and got 0 results even though there is data. 

How is this supposed to work in theory? if we put _page=2, what does it mean? If I have 100 resources, from which offset _page=2 start returning? 
Also I am supposed to first filter the results by name and then do pagination. so if we put (_page=2) in search itself, we cannot really do the filtering by name right?

Anyway, like I said, even the query you gave me, does not work. It is not throwing any errors but just gives 0 results.

**Comment by mkizesov** [comment]
@saichint
It's worth to mention that `limit()` is actually a page count `_count` parameter (yes, it's confusing).
Every FHIR server has a default page size if you don't specify it.
And if you want to control a page size, this should works:
```
# Get 1-15
client.resources('Patient').search(_page=1).limit(15).fetch()
# Get 16-30
client.resources('Patient').search(_page=2).limit(15).fetch()
```

And it's also possible to iterate searchset in for loop like this:
```
for patient in client.resources('Patient').limit(100):
        print(patient.serialize())
```

**Comment by saichint** [comment]
Understood.
So is there a way to search based on name **and** give _page=1 in the same query? If not, this will not help me much because I can only get all the patients (one page at a time) but not based on name.
If there is no other way, please close this issue after adding a comment that we can get pagination but only at the global level.
Thanks

**Comment by saichint** [comment]
Spoke too soon. Looks like it is possible.
Did this:
client.resources('Patient').search(name='Smith', _page=1).limit(2).fetch() and it worked!
Thank you very much
